### ISSUE TITLE
服务器启动不起来

### ISSUE THREAD

**Issue by Ei-M-727** [Imfdj/egg-beehive#12]
at ChildProcess.<anonymous> (/Users/mei/Downloads/node-egg/egg-beehive-main/node_modules/common-bin/lib/helper.js:56:21)
    at Object.onceWrapper (node:events:628:26)
    at ChildProcess.emit (node:events:513:28)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:293:12) {
  code: 1
}

/Users/mei/Downloads/node-egg/egg-beehive-main/node_modules/egg-cluster/lib/app_worker.js:27
  throw err;
  ^

Error: controller not exists

**Comment by Imfdj** [comment]
> at ChildProcess. (/Users/mei/Downloads/node-egg/egg-beehive-main/node_modules/common-bin/lib/helper.js:56:21) at Object.onceWrapper (node:events:628:26) at ChildProcess.emit (node:events:513:28) at Process.ChildProcess._handle.onexit (node:internal/child_process:293:12) { code: 1 }
> 
> /Users/mei/Downloads/node-egg/egg-beehive-main/node_modules/egg-cluster/lib/app_worker.js:27 throw err; ^
> 
> Error: controller not exists

1. git status 检查一下 是不是 有改动。2. node版本切换12的，重装node_modules再试试。再报错，请复制更多错误信息。
