### ISSUE TITLE
npm run dev  报错  

### ISSUE THREAD

**Issue by wwb568109135** [Imfdj/egg-beehive#9]
10011364@WWB-10011364 MINGW64 /e/demo/egg-beehive-main
$ npm run dev

> egg-beehive@1.0.0 dev
> egg-bin dev --sticky

[egg-ts-helper] create typings\app\extend\index.d.ts (4ms)
[egg-ts-helper] create typings\app\controller\index.d.ts (6ms)
[egg-ts-helper] create typings\app\middleware\index.d.ts (2ms)
[egg-ts-helper] create typings\app\model\index.d.ts (5ms)
[egg-ts-helper] create typings\config\index.d.ts (18ms)
[egg-ts-helper] create typings\config\plugin.d.ts (1ms)
[egg-ts-helper] create typings\app\service\index.d.ts (4ms)
[egg-ts-helper] create typings\app\index.d.ts (0ms)
2022-01-10 21:29:50,384 INFO 17924 [master] node version v16.13.0
2022-01-10 21:29:50,384 INFO 17924 [master] egg version 2.33.1
2022-01-10 21:29:52,121 INFO 11708 [egg-sequelize](1ms) Executed (default): SELECT 1+1 AS result
2022-01-10 21:29:52,124 INFO 17924 [master] agent_worker#1:11708 started (1736ms)
2022-01-10 21:29:54,272 ERROR 19504 nodejs.Error: controller not exists
    at resolveController (E:\demo\egg-beehive-main\node_modules\@eggjs\router\lib\egg_router.js:298:26)
    at spliteAndResolveRouterParams (E:\demo\egg-beehive-main\node_modules\@eggjs\router\lib\egg_router.js:277:20)
    at EggRouter.<computed> [as post] (E:\demo\egg-beehive-main\node_modules\@eggjs\router\lib\egg_router.js:72:25)
    at module.exports (E:\demo\egg-beehive-main\app\router.js:306:10)
    at AppWorkerLoader.loadFile (E:\demo\egg-beehive-main\node_modules\egg-core\lib\loader\egg_loader.js:304:13)
    at AppWorkerLoader.loadRouter (E:\demo\egg-beehive-main\node_modules\egg-core\lib\loader\mixin\router.js:16:10)
    at AppWorkerLoader.load (E:\demo\egg-beehive-main\node_modules\egg\lib\loader\app_worker_loader.js:43:10)
    at new Application (E:\demo\egg-beehive-main\node_modules\egg\lib\application.js:66:19)
    at Object.<anonymous> (E:\demo\egg-beehive-main\node_modules\egg-cluster\lib\app_worker.js:23:9)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:17:47

pid: 19504
hostname: WWB-10011364

E:\demo\egg-beehive-main\node_modules\egg-cluster\lib\app_worker.js:26
  throw err;
  ^

Error: controller not exists
    at resolveController (E:\demo\egg-beehive-main\node_modules\@eggjs\router\lib\egg_router.js:298:26)
    at spliteAndResolveRouterParams (E:\demo\egg-beehive-main\node_modules\@eggjs\router\lib\egg_router.js:277:20)
    at EggRouter.<computed> [as post] (E:\demo\egg-beehive-main\node_modules\@eggjs\router\lib\egg_router.js:72:25)
    at module.exports (E:\demo\egg-beehive-main\app\router.js:306:10)
    at AppWorkerLoader.loadFile (E:\demo\egg-beehive-main\node_modules\egg-core\lib\loader\egg_loader.js:304:13)
    at AppWorkerLoader.loadRouter (E:\demo\egg-beehive-main\node_modules\egg-core\lib\loader\mixin\router.js:16:10)
    at AppWorkerLoader.load (E:\demo\egg-beehive-main\node_modules\egg\lib\loader\app_worker_loader.js:43:10)
    at new Application (E:\demo\egg-beehive-main\node_modules\egg\lib\application.js:66:19)
    at Object.<anonymous> (E:\demo\egg-beehive-main\node_modules\egg-cluster\lib\app_worker.js:23:9)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:17:47
[2022-01-10 21:29:54.392] [cfork:master:17924] worker:19504 disconnect (exitedAfterDisconnect: false, state: disconnected, isDead: false, worker.disableRefork: true)
[2022-01-10 21:29:54.393] [cfork:master:17924] don't fork, because worker:19504 will be kill soon
2022-01-10 21:29:54,393 INFO 17924 [master] app_worker#1:19504 disconnect, suicide: false, state: disconnected, current workers: ["1"]
[2022-01-10 21:29:54.407] [cfork:master:17924] worker:19504 exit (code: 1, exitedAfterDisconnect: false, state: dead, isDead: true, isExpected: false, worker.disableRefork: true)
2022-01-10 21:29:54,409 ERROR 17924 nodejs.AppWorkerDiedError: [master] app_worker#1:19504 died (code: 1, signal: null, suicide: false, state: dead), current workers: []
    at Master.onAppExit (E:\demo\egg-beehive-main\node_modules\egg-cluster\lib\master.js:511:21)
    at Master.emit (node:events:390:28)
    at Messenger.sendToMaster (E:\demo\egg-beehive-main\node_modules\egg-cluster\lib\utils\messenger.js:137:17)
    at Messenger.send (E:\demo\egg-beehive-main\node_modules\egg-cluster\lib\utils\messenger.js:102:12)
    at EventEmitter.<anonymous> (E:\demo\egg-beehive-main\node_modules\egg-cluster\lib\master.js:354:22)
    at EventEmitter.emit (node:events:402:35)
    at ChildProcess.<anonymous> (node:internal/cluster/primary:203:13)
    at Object.onceWrapper (node:events:510:26)
    at ChildProcess.emit (node:events:390:28)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:290:12)
name: "AppWorkerDiedError"
pid: 17924
hostname: WWB-10011364

2022-01-10 21:29:54,411 ERROR 17924 [master] app_worker#1:19504 start fail, exiting with code:1
2022-01-10 21:29:54,411 ERROR 17924 [master] exit with code:1
Error: E:\demo\egg-beehive-main\node_modules\egg-bin\lib\start-cluster {"declarations":true,"sticky":true,"tscompiler":"ts-node/register","workers":1,"baseDir":"E:\\demo\\egg-beehive-main","framework":"E:\\demo\\egg-beehive-main\\node_modules\\egg"} exit with code 1
    at ChildProcess.<anonymous> (E:\demo\egg-beehive-main\node_modules\common-bin\lib\helper.js:56:21)
    at Object.onceWrapper (node:events:510:26)
    at ChildProcess.emit (node:events:390:28)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:290:12) {
  code: 1
}

**Comment by Imfdj** [comment]
重装依赖再试试。
可以看一下这里： https://github.com/eggjs/egg/issues/2350

**Comment by wwb568109135** [comment]
window11下，nodejs：v16.13.0  npm:8.1.0

还是不可以

**Comment by wwb568109135** [comment]
我本地 全部 跑一个egg 骨架项目，我使用官方推荐的直接使用 egg-router-plus

该 demo 就直接出现报错了，居然报错说该router的常规函数调用报错，说函数不存在（已使用很多次了）

我对比之前的项目： 我发现在typings  我发现egg-route-plus 相关依赖 都没

**Comment by wwb568109135** [comment]
今天用git clone 最新工程，npm i 一下，可以跑起来了，奇葩！
